<div class="container">
    <div class="row">
        <div class="col">

        </div>
        <div class="col">

            <?= $_SESSION["nombre_usuario"] ?>
        </div>
        <div class="col">

        </div>
    </div>
</div>

<?php
$anchura1=100;
$anchura2=40;
$anchura3=80;
?>
<table border=0 cellspacing=0 cellpadding=0>
    <tr>
        <td>
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEABsbGxscGx4hIR4qLSgtKj04MzM4PV1CR0JHQl2NWGdYWGdYjX2Xe3N7l33gsJycsOD/2c7Z//////////////8BGxsbGxwbHiEhHiotKC0qPTgzMzg9XUJHQkdCXY1YZ1hYZ1iNfZd7c3uXfeCwnJyw4P/Zztn////////////////CABEIAPoA+gMBIgACEQEDEQH/xAAXAAEBAQEAAAAAAAAAAAAAAAAAAQMF/9oACAEBAAAAAOeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFgAAAAFgAAAAAAAAAAAAAAALAAAAKhr//EABcBAQEBAQAAAAAAAAAAAAAAAAABBAb/2gAKAgIQAxAAAADF0oAAAABQARQAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBAAAAAAAAAAAAWf/EABkQAQACAwAAAAAAAAAAAAAAAAEAETFAkP/aAAgBAQABPwDvA5d8Cif/xAAUEQEAAAAAAAAAAAAAAAAAAACA/9oACAECAQE/AAB//8QAFhEBAQEAAAAAAAAAAAAAAAAAAQBw/9oACAEDAQE/AN/W/9k="
                width="<?php echo $anchura1?>" height="20">
        </td>
    </tr>
    <tr>
        <td>
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAsJCQcJCQcJCQkJCwkJCQkJCQsJCwsMCwsLDA0QDBEODQ4MEhkSJRodJR0ZHxwpKRYlNzU2GioyPi0pMBk7IRP/2wBDAQcICAsJCxULCxUsHRkdLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCz/wAARCAC0AK0DASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAP/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFwEBAQEBAAAAAAAAAAAAAAAAAAEGB//EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALAOUMGACAAAAAAAAAAAAAAAAAAAAoAIAAAAAAAAAAAAAAAAAAACgAgAAAAAAAAAAAAAAAAAAAKACAAAAAAAAAAAAAAAAAAAAoAIAAAAAAAAAAAAAAAAAAACgAgAAAAAAAAAAAAAAAAAAAKACAAAAAAAAAAAAAAAAAAAAoAIAAAAAAAAAAAAAAAAAAACgAgAAAAAAAAAAAAAAAAAAAKACAAAAAAAAAAAAAAAAAAAAoAIAAAAAAAAAAAAAAAAAAACgAgAAAAAAAAAAAAAAAAAD//Z"
                width="<?php echo $anchura2?>" height="20">
        </td>
    </tr>
    <tr>
        <td>
            <img src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAsJCQcJCQcJCQkJCwkJCQkJCQsJCwsMCwsLDA0QDBEODQ4MEhkSJRodJR0ZHxwpKRYlNzU2GioyPi0pMBk7IRP/2wBDAQcICAsJCxULCxUsHRkdLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCz/wAARCAC2AIEDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAECB//EABgQAQEBAQEAAAAAAAAAAAAAAAARASGB/8QAGQEBAQEBAQEAAAAAAAAAAAAAAAECAwUH/8QAGhEBAQEBAQEBAAAAAAAAAAAAAAERAhIhMf/aAAwDAQACEQMRAD8A58VB9BnEeHpdW6gvmC09QXzEaujIvmCrWRfItKgmCpSonmKogzeYLQGcUSmjrGQRVABZAq1BoWnEAVATAATAAYqggwq6LqOjIA1gANAAoKiiIAigAAI51VAYxV1DRuMgQbgAKACgAAAgAgAaYxVUBz+tGgNxgAagANAAoCoAAgAgADFVRBjVXReIs/EQBoUBtAAABQAQEVEtABiqAJooJ1OaADYoh1dRRFWUAABAABlQBmgAxqqgHBQRXQABABQAXQANBAZUURnoUBzQBGuatAHQFQBRBUVAQVAFAAAHPqgAxoANRaAOkQAUAAUQAAADWWLTGisqxVxaIMGKA1FAG4yALKCoq6CAmgUTU0ggI0CDNXF6IMmNgEQAaF4AGABphwmgCEBn1USEBdUiQGeqpAHPaP/Z"
                width="<?php echo $anchura3?>" height="20">
        </td>
    </tr>
</table>